name = "CreateServer - Client"
author = "Miner90027"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca494808d29982108a47b295275453a8bbce0f084166befa012e07ee4b501ec6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
unsup = "1.2.7"
