name = "CreateServer - Client"
author = "Miner90027"
version = "3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b1dd02be6860ac9a84883fd782d1bdea6e2d1800e1ac99b17036c8ce1cb7701"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
unsup = "1.2.7"
